name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Pull from Notion
        env:
          DOCU_NOTION_INTEGRATION_TOKEN: ${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}
          DOCU_NOTION_SAMPLE_ROOT_PAGE: ${{ secrets.DOCU_NOTION_SAMPLE_ROOT_PAGE }}
        run: yarn pull
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply changes from docu-notion
      - name: Build github pages branch
        run: yarn build
      - name: Install serve
        run: yarn global add serve
      - name: Start local server
        run: |
          serve -s build -l 3000 &
          sleep 5
          
      - name: Clone your forked docu-pdf
        run: git clone -b test --single-branch https://github.com/rhanak1/docu-pdf.git

      - name: Install dependencies for docu-pdf
        run: cd docu-pdf && yarn install

      - name: Generate PDF with your forked docu-pdf
        run: npx ts-node docu-pdf/src/cli.ts http://localhost:3000

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: ./site.pdf
      #- name: Deploy to gh-pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./build
