name: Release
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: false
        default: "warning"
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Install dependencies
        run: yarn
      - name: Pull from Notion
        env:
          DOCU_NOTION_INTEGRATION_TOKEN: ${{ secrets.DOCU_NOTION_INTEGRATION_TOKEN }}
          DOCU_NOTION_SAMPLE_ROOT_PAGE: ${{ secrets.DOCU_NOTION_SAMPLE_ROOT_PAGE }}
        run: yarn pull
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply changes from docu-notion
      
      - name: Build github pages branch
        run: yarn build
      #- name: Install serve
      #  run: yarn global add serve

      #- name: Deploy to gh-pages
      #  uses: peaceiris/actions-gh-pages@v3
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      #    publish_dir: ./build

      - name: Install http-server
        run: npm install -g http-server

      - name: Start static server
        run: http-server ./build -p 3000 -s &

      - name: Test page accessibility
        run: |
          curl -I http://localhost:3000/docs/docu-notion-sample-site/
          curl -I http://localhost:3000/docs/docu-notion-sample-site/windows-installation
          curl -I http://localhost:3000/docs/docu-notion-sample-site/docu-notion-sample-site/installing-scripture-app-builder
          curl -I http://localhost:3000/docs/docu-notion-sample-site/installing-jdk
          curl -I http://localhost:3000/docs/docu-notion-sample-site/install-jdk-wizard
          curl -I http://localhost:3000/docs/docu-notion-sample-site/installing-jdk-from-Azul
      
      #- name: Wait for server to be up
       # run: |
        #    until curl -s http://localhost:3000 > /dev/null; do
         #   echo "Waiting for server..."
          #  sleep 1
           # done
            
      - name: Disable AppArmor
        # Ubuntu >= 23 has AppArmor enabled by default, which breaks Puppeteer.
        # See https://github.com/puppeteer/puppeteer/issues/12818 "No usable sandbox!"
        # this is taken from the solution used in Puppeteer's own CI: https://github.com/puppeteer/puppeteer/pull/13196
        # The alternative is to pin Ubuntu 22 or to use aa-exec to disable AppArmor for commands that need Puppeteer.
        # This is also suggested by Chromium https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns
        shell: bash
        
      - name: Generate PDF
        run: npx docu-pdf http://localhost:3000

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: ./site.pdf
          
      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docusaurus-site
          path: build/

